// js/data.js
// Expanded curated dataset — 30 business models with in-depth consultant-style fields.
// Add more entries later if needed.

export const BUSINESSES = [
  {
    id: "faceless-youtube",
    title: "Faceless YouTube Channel",
    type: "service",
    skills: ["video-editing","script-research","voiceover","thumbnail-design"],
    interests: ["media","education","entertainment"],
    timePerDay: "1-4 hrs",
    income_1_3_months: "₹2k - ₹25k",
    difficulty: "Medium",
    trend: "High",
    summary: "Create niche faceless videos (explainers, listicles, AI voiceovers) and monetize via AdSense, affiliates and sponsorships.",
    how: [
      "Identify niche & audience (topical + evergreen)",
      "Create content calendar & batch-produce scripts",
      "Use SEO-optimized titles, descriptions & thumbnails",
      "Monetize: AdSense, affiliate links, channel membership"
    ],
    requirements: [
      "Basic storytelling & scriptwriting",
      "Editing skills (Premiere/DaVinci/CapCut)",
      "Thumbnail design & basic SEO knowledge"
    ],
    startupCost: "₹8,000 - ₹35,000",
    tools: ["YouTube Studio","Descript","CapCut","Canva","TubeBuddy"],
    marketingChannels: ["YouTube search & suggested","Shorts","Reddit niche communities","Pinterest"],
    revenueStreams: ["Adsense","Affiliate marketing","Sponsored videos","Merch"],
    kpis: ["Watch time","Click-through rate (CTR)","RPM","Subscriber growth"],
    legal: "Use licensed music; disclose sponsored content and affiliate links.",
    pitfalls: "Ignoring thumbnail A/B tests, inconsistent upload schedule, poor SEO."
  },

  {
    id: "instagram-theme-page",
    title: "Instagram Theme Page (Curated)",
    type: "product",
    skills: ["visual-curation","short-video-editing","copywriting"],
    interests: ["fashion","lifestyle","aesthetics"],
    timePerDay: "0.5-3 hrs",
    income_1_3_months: "₹1k - ₹20k",
    difficulty: "Low",
    trend: "Medium",
    summary: "Grow a niche aesthetic page—monetize with shoutouts, affiliate links and dropshipping referral links.",
    how: [
      "Pick tight visual theme & content pillars",
      "Post daily: 1 reel + 1 carousel",
      "Use UGC and curated content with credit",
      "Monetize via shoutouts, affiliate links, DM sales"
    ],
    requirements: ["Eye for visuals","Reel editing basics","Hashtag & caption strategy"],
    startupCost: "₹1,000 - ₹10,000",
    tools: ["Canva","InShot","Later/Planoly","Linktree"],
    marketingChannels: ["Instagram Reels","Collaborations","TikTok cross-posting"],
    revenueStreams: ["Paid shoutouts","Affiliate commissions","Digital templates","Sponsorships"],
    kpis: ["Engagement rate","Follower growth","Saves & shares","Link clicks"],
    legal: "Disclose paid posts; respect copyrights when reposting images.",
    pitfalls: "Poor niche focus, buying fake followers, inconsistent aesthetics."
  },

  {
    id: "freelance-website-dev",
    title: "Freelance Web Developer (React/Vanilla)",
    type: "service",
    skills: ["html","css","javascript","react","deployment"],
    interests: ["tech","business"],
    timePerDay: "2-6 hrs",
    income_1_3_months: "₹10k - ₹80k",
    difficulty: "Medium",
    trend: "High",
    summary: "Build sites for businesses; start with small local clients and scale to higher-ticket agency work.",
    how: [
      "Build 3 polished portfolio samples",
      "List services on freelancing platforms",
      "Narrow to 1-2 industries for niche expertise",
      "Systematize proposals & onboarding"
    ],
    requirements: ["Portfolio","GitHub","Basic SEO & responsive design knowledge"],
    startupCost: "₹2,000 - ₹20,000",
    tools: ["VSCode","Git/GitHub","Vercel/Netlify","Figma","Stripe/UPI"],
    marketingChannels: ["LinkedIn outreach","Local networking","Upwork/Fiverr","Referrals"],
    revenueStreams: ["Fixed-price projects","Retainers (maintenance)","Templates & themes"],
    kpis: ["Avg. project value","Close rate","Client retention","Utilization"],
    legal: "Contracts for scope, milestones & IP ownership; GST registration if applicable.",
    pitfalls: "Scope creep, not using contracts, poor communication."
  },

  {
    id: "print-on-demand",
    title: "Print-on-Demand (T-shirts & Mugs)",
    type: "product",
    skills: ["graphic-design","market-research","product-listing"],
    interests: ["fashion","art","ecommerce"],
    timePerDay: "1-3 hrs",
    income_1_3_months: "₹2k - ₹25k",
    difficulty: "Low",
    trend: "Medium",
    summary: "Design products and sell via POD platforms—low risk inventory model.",
    how: [
      "Research micro-niches & validate designs",
      "Create 20 designs & upload to POD",
      "Run targeted ads & optimize listings",
      "Scale by expanding SKUs & marketplaces"
    ],
    requirements: ["Basic design skills","Understanding of margins and mockups"],
    startupCost: "₹2,000 - ₹15,000",
    tools: ["Printful","Shopify","Etsy","Canva","Photoshop"],
    marketingChannels: ["Instagram ads","Facebook groups","Pinterest","SEO on Etsy"],
    revenueStreams: ["Item sales","Bundle offers","Limited drops"],
    kpis: ["Conversion rate","Average order value","Ad ROAS","Profit margin"],
    legal: "Avoid copyrighted designs; verify trademark issues.",
    pitfalls: "Poor niche selection, underpricing, ignoring shipping times."
  },

  {
    id: "affiliate-marketing-blog",
    title: "Affiliate Marketing Blog (SEO)",
    type: "service",
    skills: ["seo","writing","keyword-research","affiliate-strategy"],
    interests: ["tech","products","personal-finance"],
    timePerDay: "1-3 hrs",
    income_1_3_months: "₹0 - ₹15k",
    difficulty: "High",
    trend: "High",
    summary: "Build niche content sites that convert via affiliate links—long-term, compounding income.",
    how: [
      "Target low-competition buyer keywords",
      "Write long-form, review & comparison posts",
      "Optimize on-page SEO & link-building",
      "Scale by adding more pages and content clusters"
    ],
    requirements: ["Content writing skills","Basic on-page & off-page SEO"],
    startupCost: "₹5,000 - ₹30,000",
    tools: ["WordPress","Ahrefs/SEMrush (optional)","Google Search Console","Elementor"],
    marketingChannels: ["Organic search","Pinterest","YouTube repurposing"],
    revenueStreams: ["Affiliate commissions","Display ads","Email funnels"],
    kpis: ["Organic traffic","Affiliate CTR","EPC (earnings per click)","DA/DR growth"],
    legal: "Disclose affiliate links; follow platform affiliate program rules.",
    pitfalls: "Chasing high-competition keywords too early; thin content."
  },

  {
    id: "dropshipping-store",
    title: "Dropshipping (Niche Store)",
    type: "product",
    skills: ["product-research","ads","shop-management"],
    interests: ["ecommerce","gadgets","home"],
    timePerDay: "1-4 hrs",
    income_1_3_months: "₹0 - ₹40k",
    difficulty: "Medium",
    trend: "Variable",
    summary: "Sell trending products via a storefront without holding inventory; rely on supplier fulfillment.",
    how: [
      "Validate products with cheap traffic tests",
      "Set up store & landing pages",
      "Run targeted ads & optimize funnels",
      "Move winners to branded inventory if scaling"
    ],
    requirements: ["Basic ads knowledge (Meta/Google)","Supplier vetting skills"],
    startupCost: "₹8,000 - ₹60,000",
    tools: ["Shopify","Oberlo/DSers","Stripe/PayPal","Meta Ads Manager"],
    marketingChannels: ["Meta ads","Google Shopping","Influencer seeding"],
    revenueStreams: ["Product margin","Upsells","Email remarketing"],
    kpis: ["Return on ad spend (ROAS)","CR","CAC","Return rate"],
    legal: "Clear refund policy; ensure supplier reliability; GST compliance.",
    pitfalls: "Unreliable suppliers, poor margins, overspending on ads."
  },

  {
    id: "digital-products",
    title: "Digital Products (Courses & Templates)",
    type: "product",
    skills: ["course-creation","instructional-design","launch-marketing"],
    interests: ["education","professional-growth"],
    timePerDay: "1-4 hrs",
    income_1_3_months: "₹5k - ₹80k",
    difficulty: "Medium",
    trend: "High",
    summary: "Create information products — courses, templates, presets — sell repeatedly with low marginal cost.",
    how: [
      "Choose high-demand pain point",
      "Outline curriculum & record short modules",
      "Host on a course platform & build sales page",
      "Run a launch / evergreen funnel"
    ],
    requirements: ["Domain expertise or case studies","Basic video/audio editing"],
    startupCost: "₹10,000 - ₹75,000",
    tools: ["Teachable","Gumroad","Loom","Camtasia","Stripe"],
    marketingChannels: ["Email list","Webinars","Paid ads","YouTube"],
    revenueStreams: ["Course sales","Memberships","Affiliate/referral"],
    kpis: ["Conversion rate","Avg. order value","Churn (if membership)","LTV"],
    legal: "Clear terms of use; refund policy; avoid copyrighted material.",
    pitfalls: "Overlong courses, poor learning outcomes, no marketing plan."
  },

  {
    id: "social-media-influencer",
    title: "Social Media Influencer (Niche Creator)",
    type: "service",
    skills: ["content-creation","community-building","negotiation"],
    interests: ["lifestyle","fitness","beauty"],
    timePerDay: "2-6 hrs",
    income_1_3_months: "₹5k - ₹1,00,000+",
    difficulty: "High",
    trend: "High",
    summary: "Create consistent on-platform content and monetize via brand deals, affiliate links and merchandise.",
    how: [
      "Pick niche & signature content format",
      "Post daily (mix of short + long form)",
      "Build media kit & pitch brands",
      "Diversify revenue: affiliates, merch, paid content"
    ],
    requirements: ["Camera confidence","Basic editing","Brand pitch templates"],
    startupCost: "₹5,000 - ₹50,000",
    tools: ["Instagram/TikTok/YouTube","Canva","Later","Google Sheets"],
    marketingChannels: ["Platform algorithms (Reels/TikTok/Shorts)","Collaborations","Podcasts"],
    revenueStreams: ["Sponsored posts","Affiliate commissions","Merch","Appearances"],
    kpis: ["Engagement rate","CPM for sponsorships","Follower growth","Story swipe ups"],
    legal: "Honor sponsored disclosures; contracts for deals; music licensing rules.",
    pitfalls: "Chasing vanity metrics, inconsistent posting, ignoring community."
  },

  {
    id: "social-media-manager",
    title: "Social Media Manager (Agency/Freelance)",
    type: "service",
    skills: ["strategy","content-planning","ads","analytics"],
    interests: ["marketing","brands","growth"],
    timePerDay: "2-6 hrs",
    income_1_3_months: "₹15k - ₹2,00,000",
    difficulty: "Medium",
    trend: "High",
    summary: "Offer end-to-end social media management: content, community, ads and reporting for SMBs.",
    how: [
      "Define packages: content, ads, reporting",
      "Build case studies & sample calendars",
      "Automate posting & reporting",
      "Scale via hires or white-labeling"
    ],
    requirements: ["Portfolio/case studies","Content templates & SOPs"],
    startupCost: "₹3,000 - ₹25,000",
    tools: ["Hootsuite/Later","Canva","Meta Ads Manager","Google Analytics"],
    marketingChannels: ["LinkedIn outreach","Referrals","Content marketing"],
    revenueStreams: ["Monthly retainers","Ad management fees","Creative add-ons"],
    kpis: ["Impressions","Engagement","Leads generated","Client retention"],
    legal: "Contracts with scope, NDAs; ad compliance rules per platform.",
    pitfalls: "Overpromising results, lack of measurement, not using contracts."
  },

  {
    id: "saas-microproduct",
    title: "Micro-SaaS (Single-feature product)",
    type: "product",
    skills: ["product-design","backend-dev","customer-support"],
    interests: ["productivity","developer-tools","marketing"],
    timePerDay: "1-4 hrs",
    income_1_3_months: "₹0 - ₹1,00,000+",
    difficulty: "High",
    trend: "High",
    summary: "Build a focused SaaS solving one clear problem for a niche — aim for recurring revenue.",
    how: [
      "Validate problem via interviews & landing page",
      "Build MVP & onboarding flow",
      "Charge subscription & iterate with user feedback",
      "Invest in retention and support"
    ],
    requirements: ["Technical ability or co-founder","Understanding of subscription metrics"],
    startupCost: "₹30,000 - ₹3,00,000",
    tools: ["Vercel/Heroku","Stripe","Postgres/MongoDB","Sentry","Intercom"],
    marketingChannels: ["Content marketing","Product Hunt","Developer communities"],
    revenueStreams: ["Monthly/annual subscriptions","Enterprise licensing","Add-on services"],
    kpis: ["MRR","ARR","Churn rate","CAC payback period"],
    legal: "Data privacy (user data), TOS, GDPR considerations if EU users.",
    pitfalls: "Feature bloat, ignoring unit economics, poor onboarding."
  },

  {
    id: "virtual-assistant-services",
    title: "Virtual Assistant (Niche: Creators/SMBs)",
    type: "service",
    skills: ["email-management","scheduling","social-media-support"],
    interests: ["productivity","operations"],
    timePerDay: "2-6 hrs",
    income_1_3_months: "₹10k - ₹60k",
    difficulty: "Low",
    trend: "Medium",
    summary: "Offer admin and operational support remotely—package by hours or tasks.",
    how: [
      "Define service packages (hours per month)",
      "Create SOPs for common tasks",
      "Use time-tracking and onboarding forms",
      "Upsell specialized services (email funnels, customer support)"
    ],
    requirements: ["Strong communication","Tool familiarity (calendars, CRMs)"],
    startupCost: "₹1,000 - ₹8,000",
    tools: ["Google Workspace","Trello/Asana","Calendly","Zoom"],
    marketingChannels: ["Upwork","LinkedIn","Referrals","Virtual assistant job boards"],
    revenueStreams: ["Hourly retainer","Package fees","Add-ons"],
    kpis: ["Billable hours","Client retention","Utilization rate"],
    legal: "Confidentiality agreements; data handling policies.",
    pitfalls: "Undercharging, poor boundaries, scope creep."
  },

  {
    id: "online-tutoring",
    title: "Online Tutoring / Coaching",
    type: "service",
    skills: ["subject-matter-expertise","lesson-planning","student-assessment"],
    interests: ["education","skill-building"],
    timePerDay: "2-5 hrs",
    income_1_3_months: "₹5k - ₹80k",
    difficulty: "Low",
    trend: "High",
    summary: "Teach students online one-on-one or in small groups; offer packages and recurring classes.",
    how: [
      "Define target student and outcomes",
      "Create curriculum & sample lessons",
      "List on tutoring marketplaces & run ads",
      "Collect testimonials and referrals"
    ],
    requirements: ["Proof of competence (certs or results)","Teaching tools knowledge"],
    startupCost: "₹1,000 - ₹15,000",
    tools: ["Zoom","Google Classroom","Kahoot","Notion"],
    marketingChannels: ["Parent groups","YouTube content","Tutoring platforms"],
    revenueStreams: ["Hourly fees","Course bundles","Group classes"],
    kpis: ["Student retention","Lesson completion rate","Referrals"],
    legal: "Child protection policies if tutoring minors; clear refund terms.",
    pitfalls: "Lack of structure, poor lesson planning, inconsistent availability."
  },

  {
    id: "podcast-creator",
    title: "Podcast Creator (Niche)",
    type: "service",
    skills: ["audio-editing","storytelling","guest-outreach"],
    interests: ["media","education","conversations"],
    timePerDay: "1-3 hrs",
    income_1_3_months: "₹0 - ₹50k",
    difficulty: "Medium",
    trend: "Medium",
    summary: "Launch a niche podcast, grow listeners and monetize with sponsors, premium episodes or memberships.",
    how: [
      "Plan format & episode cadence",
      "Record and batch edit episodes",
      "Distribute to major podcast platforms",
      "Monetize through sponsorships & memberships"
    ],
    requirements: ["Good mic & editing basics","Interviewing skills"],
    startupCost: "₹5,000 - ₹50,000",
    tools: ["Audacity/Descript","Anchor/Libsyn","Canva","Patreon"],
    marketingChannels: ["YouTube repurposing","Newsletter","Guest cross-promotion"],
    revenueStreams: ["Sponsorships","Listener support (Patreon)","Live events"],
    kpis: ["Downloads per episode","Retention","Ad CPM"],
    legal: "Music licensing; guest release forms.",
    pitfalls: "Infrequent publishing, poor audio quality, unclear niche."
  },

  {
    id: "local-events-planner",
    title: "Local Events & Experiences",
    type: "service",
    skills: ["logistics","vendor-management","marketing"],
    interests: ["community","experiences"],
    timePerDay: "2-6 hrs",
    income_1_3_months: "₹10k - ₹1,50,000",
    difficulty: "Medium",
    trend: "Medium",
    summary: "Organize pop-ups, workshops, and experiences for local audiences—charge ticket fees and sponsors.",
    how: [
      "Scout venues & vendors",
      "Design experience & pricing",
      "Promote via local channels",
      "Collect feedback & build repeat customers"
    ],
    requirements: ["Permits & vendor contacts","Event insurance knowledge"],
    startupCost: "₹15,000 - ₹2,00,000 (depends on event size)",
    tools: ["Eventbrite/BookMyShow","Canva","Stripe","WhatsApp/Telegram"],
    marketingChannels: ["Local FB groups","Instagram","College networks"],
    revenueStreams: ["Ticket sales","Sponsorships","Merch & F&B cut"],
    kpis: ["Ticket sell-through","Net margin per event","NPS"],
    legal: "Venue contracts, permits, liability insurance.",
    pitfalls: "Underestimating costs, poor vendor contracts, low attendance."
  },

  {
    id: "stock-photography",
    title: "Stock Photography & Asset Licensing",
    type: "product",
    skills: ["photography","editing","keywording"],
    interests: ["photography","design"],
    timePerDay: "1-3 hrs",
    income_1_3_months: "₹0 - ₹30k",
    difficulty: "Low",
    trend: "Medium",
    summary: "Shoot high-demand images and license via stock platforms or direct clients.",
    how: [
      "Research in-demand photo topics",
      "Shoot consistent collections & edit",
      "Upload to multiple stock agencies",
      "Promote via niche portfolios"
    ],
    requirements: ["Camera & editing skills","Understanding of licensing"],
    startupCost: "₹10,000 - ₹1,00,000",
    tools: ["Adobe Lightroom/Photoshop","Shutterstock","Adobe Stock","500px"],
    marketingChannels: ["Portfolio websites","Instagram","Pinterest"],
    revenueStreams: ["Microstock royalties","Direct licensing","Print sales"],
    kpis: ["Downloads per photo","Earnings per download","Portfolio growth"],
    legal: "Model releases for people, property releases for private locations.",
    pitfalls: "Skipping keywording, low-quality uploads, ignoring model/property releases."
  },

  {
    id: "amazon-fba",
    title: "Amazon FBA (Private Label)",
    type: "product",
    skills: ["sourcing","supply-chain","listing-optimization"],
    interests: ["ecommerce","product-development"],
    timePerDay: "1-4 hrs",
    income_1_3_months: "₹0 - ₹2,00,000+",
    difficulty: "High",
    trend: "Medium",
    summary: "Source products, brand them, and use Amazon FBA for fulfillment at scale.",
    how: [
      "Perform product research & margin analysis",
      "Source manufacturer & order samples",
      "Optimize listings & run PPC",
      "Monitor reviews & scale inventory"
    ],
    requirements: ["Sourcing skills and capital","Understanding of Amazon policies"],
    startupCost: "₹50,000 - ₹6,00,000",
    tools: ["Jungle Scout/Helium 10","Alibaba","Amazon Seller Central","Keepa"],
    marketingChannels: ["Amazon PPC","External traffic (Facebook/Google)","Influencers"],
    revenueStreams: ["Product sales","Bundling & variations"],
    kpis: ["Unit economics","Inventory turnover","ACoS","Customer review rating"],
    legal: "GST, import duty, trademark checks; follow Amazon rules to avoid suspensions.",
    pitfalls: "Poor supplier vetting, inventory stockouts or excess, margin erosion from fees."
  },

  {
    id: "handmade-crafts",
    title: "Handmade Crafts & Art (Etsy)",
    type: "product",
    skills: ["craftsmanship","product-photography","listing-copy"],
    interests: ["art","handmade","gifting"],
    timePerDay: "1-5 hrs",
    income_1_3_months: "₹2k - ₹60k",
    difficulty: "Low",
    trend: "Medium",
    summary: "Create handcrafted products and sell on Etsy or direct via Shopify/Instagram.",
    how: [
      "Design a small product line",
      "Perfect packaging & photography",
      "List with clear shipping policies",
      "Scale with custom orders & collaborations"
    ],
    requirements: ["Production process & quality control","Shipping knowledge"],
    startupCost: "₹5,000 - ₹50,000",
    tools: ["Etsy shop","Shopify","Canva","ShipRocket/IndiaPost"],
    marketingChannels: ["Etsy search","Instagram","Local craft fairs"],
    revenueStreams: ["Product sales","Custom commissions","Workshops"],
    kpis: ["Conversion rate","Repeat customer rate","Average order value"],
    legal: "Comply with handmade labeling; consider trademarks for brand.",
    pitfalls: "Underpricing, poor packaging, ignoring shipping costs."
  },

  {
    id: "online-marketing-agency",
    title: "Digital Marketing Agency (Niche)",
    type: "service",
    skills: ["strategy","ads","analytics","content"],
    interests: ["growth","brands","tech"],
    timePerDay: "3-8 hrs",
    income_1_3_months: "₹50k - ₹5,00,000+",
    difficulty: "High",
    trend: "High",
    summary: "Offer specialized digital marketing services (e.g., e-comm, local SEO) as an agency with recurring retainers.",
    how: [
      "Pick 1-2 niches & build case studies",
      "Create clear retainer packages",
      "Automate reporting & scale with hires",
      "Invest in sales & operations processes"
    ],
    requirements: ["Proven results & team to deliver","SOPs & contracts"],
    startupCost: "₹20,000 - ₹2,00,000",
    tools: ["Google Ads","Meta Ads","SEMrush","Data Studio","Slack"],
    marketingChannels: ["Outbound sales","LinkedIn","Referrals","Content marketing"],
    revenueStreams: ["Retainers","Project fees","Revenue share deals"],
    kpis: ["MRR","Client LTV","Utilization","Client ROI"],
    legal: "Service contracts, scope, liability clauses; GST & accounting.",
    pitfalls: "Scaling too fast, client churn, lack of documented processes."
  },

  {
    id: "subscription-box",
    title: "Subscription Box (Curated Goods)",
    type: "product",
    skills: ["curation","supply-chain","customer-retention"],
    interests: ["lifestyle","wellness","food"],
    timePerDay: "1-4 hrs",
    income_1_3_months: "₹20k - ₹2,00,000",
    difficulty: "Medium",
    trend: "Variable",
    summary: "Deliver curated monthly boxes for a niche (snacks, self-care) with recurring revenue.",
    how: [
      "Define theme & price point",
      "Source products & negotiate supplier deals",
      "Build sign-up funnel & manage fulfillment",
      "Focus on retention with personalization"
    ],
    requirements: ["Fulfillment setup & vendor relationships","Customer service"],
    startupCost: "₹50,000 - ₹5,00,000",
    tools: ["Recharge/Cratejoy","ShipRocket","Stripe","Klaviyo"],
    marketingChannels: ["Influencers","Email marketing","Facebook ads"],
    revenueStreams: ["Subscriptions","Add-on sales","Corporate boxes"],
    kpis: ["MRR","Churn","Subscriber acquisition cost","LTV"],
    legal: "Clear T&Cs, allergen labeling for food boxes, supplier contracts.",
    pitfalls: "High churn, poor unit economics, logistical failures."
  },

  {
    id: "ui-ux-design-freelance",
    title: "UI/UX Designer (Freelance)",
    type: "service",
    skills: ["figma","user-research","prototyping","usability-testing"],
    interests: ["product","design","saas"],
    timePerDay: "2-6 hrs",
    income_1_3_months: "₹20k - ₹1,00,000+",
    difficulty: "Medium",
    trend: "High",
    summary: "Design high-converting product experiences & prototypes for startups and SMBs.",
    how: [
      "Build case studies with process-driven case studies",
      "Offer discovery -> prototype -> handoff packages",
      "Use design systems to speed delivery",
      "Upsell usability testing & iterations"
    ],
    requirements: ["Portfolio with process, not just visuals","Prototyping tools knowledge"],
    startupCost: "₹2,000 - ₹25,000",
    tools: ["Figma","Maze","Notion","Zeplin"],
    marketingChannels: ["Dribbble/Behance","LinkedIn","Referrals"],
    revenueStreams: ["Project fees","Retainers","Design templates"],
    kpis: ["Project margin","Repeat business","Time to first prototype"],
    legal: "IP clauses in contracts; NDA for sensitive projects.",
    pitfalls: "Portfolio without results, lack of client discovery, vague scope."
  },

  {
    id: "content-repurposing",
    title: "Content Repurposing Service",
    type: "service",
    skills: ["editing","short-form strategy","copywriting"],
    interests: ["media","creators","marketing"],
    timePerDay: "1-4 hrs",
    income_1_3_months: "₹10k - ₹80k",
    difficulty: "Low",
    trend: "High",
    summary: "Turn long-form content (podcast/video) into social clips, carousels & newsletters for creators.",
    how: [
      "Define deliverable packages (clips per month, carousels)",
      "Create templates & editing SOPs",
      "Offer a fast turnaround & performance reporting",
      "Scale with junior editors"
    ],
    requirements: ["Editing workflow & templates","Understanding of each platform's specs"],
    startupCost: "₹2,000 - ₹25,000",
    tools: ["Descript","CapCut","Canva","Airtable"],
    marketingChannels: ["Creator communities","Cold outreach","Upwork"],
    revenueStreams: ["Monthly retainers","One-off packages"],
    kpis: ["Deliverable throughput","Client retention","Content engagement uplift"],
    legal: "Content use rights; client approval process.",
    pitfalls: "Low quality excerpts, slow turnaround, poor version control."
  },

  {
    id: "niche-job-board",
    title: "Niche Job Board (Subscription)",
    type: "product",
    skills: ["community-building","product-management","seo"],
    interests: ["hiring","recruiting","vertical SaaS"],
    timePerDay: "1-3 hrs",
    income_1_3_months: "₹5k - ₹2,00,000",
    difficulty: "Medium",
    trend: "Medium",
    summary: "Create a job board focused on a specific industry (e.g., remote devs from India) with paid listings & subscriptions.",
    how: [
      "Validate niche demand with landing page",
      "Build job-posting & candidate browsing features",
      "Seed listings & companies",
      "Charge per listing and offer monthly subscriptions"
    ],
    requirements: ["Basic marketplace design","Outbound sales to companies"],
    startupCost: "₹20,000 - ₹2,00,000",
    tools: ["WordPress + WP Job Manager","Stripe","Algolia","Mailgun"],
    marketingChannels: ["LinkedIn","Niche newsletters","SEO for job queries"],
    revenueStreams: ["Paid job posts","Featured listings","Candidate subscriptions"],
    kpis: ["Listings per month","Fill rate","Repeat employer rate"],
    legal: "Terms for employers; data privacy for candidate resumes.",
    pitfalls: "Two-sided marketplace cold start, undervaluing listings."
  },

  {
    id: "local-consulting",
    title: "Local Business Consultant (SMB Growth)",
    type: "service",
    skills: ["operations","marketing","finance"],
    interests: ["small-business","retail","F&B"],
    timePerDay: "2-6 hrs",
    income_1_3_months: "₹20k - ₹2,00,000",
    difficulty: "Medium",
    trend: "Stable",
    summary: "Help local businesses increase footfall & revenue via operations optimization and local marketing.",
    how: [
      "Audit current operations & financials",
      "Create prioritized growth plan",
      "Implement local SEO & simple ads",
      "Offer training & monthly check-ins"
    ],
    requirements: ["Case studies/market knowledge","Proven ROI frameworks"],
    startupCost: "₹2,000 - ₹25,000",
    tools: ["Google My Business","WhatsApp Business","Sheets"],
    marketingChannels: ["Local ads","Partnerships","Flyers"],
    revenueStreams: ["Consulting fees","Commission on improvements","Workshops"],
    kpis: ["Revenue uplift %","Customer acquisition cost","Repeat customer rate"],
    legal: "Consulting contract with deliverables & payment terms.",
    pitfalls: "Overpromising, lack of measurable outcomes, misaligned expectations."
  },

  {
    id: "resell-service",
    title: "Reselling (Sneakers/Streetwear)",
    type: "product",
    skills: ["sourcing","market-analysis","authenticity-checks"],
    interests: ["fashion","collectibles"],
    timePerDay: "1-4 hrs",
    income_1_3_months: "₹5k - ₹2,00,000+",
    difficulty: "Medium",
    trend: "Variable",
    summary: "Buy limited-edition items and resell at a markup via marketplaces or Instagram.",
    how: [
      "Identify high-demand drops & market prices",
      "Set up buy strategy & automation where allowed",
      "List on platforms & build trust via authenticity checks",
      "Expand to private clients and consignments"
    ],
    requirements: ["Capital for inventory","Knowledge of authenticity methods"],
    startupCost: "₹10,000 - ₹2,00,000",
    tools: ["StockX/BGO/Platform accounts","Instagram","Payment gateways"],
    marketingChannels: ["Instagram","Discord communities","Marketplaces"],
    revenueStreams: ["Resale margin","Consignment fees"],
    kpis: ["Inventory turnover","Gross margin","Sell-through rate"],
    legal: "Be aware of platform rules and counterfeit laws.",
    pitfalls: "Holding too much inventory, fakes, pricing volatility."
  },

  {
    id: "3d-printing-hardware",
    title: "3D Printing (Custom Parts & Prototypes)",
    type: "service",
    skills: ["3d-modelling","printer-ops","finishing"],
    interests: ["hardware","product-development","prototyping"],
    timePerDay: "1-5 hrs",
    income_1_3_months: "₹5k - ₹1,50,000",
    difficulty: "Medium",
    trend: "Niche",
    summary: "Offer prototyping and small-batch manufacturing using 3D printers for local designers and makers.",
    how: [
      "Invest in reliable printers & materials",
      "Offer prototyping & finishing services",
      "Create catalog of common parts for quick orders",
      "Partner with designers & local startups"
    ],
    requirements: ["Printer maintenance skills","CAD proficiency"],
    startupCost: "₹30,000 - ₹5,00,000",
    tools: ["Cura/PrusaSlicer","Fusion 360/Blender","3D printers"],
    marketingChannels: ["Maker communities","LinkedIn","Local meetups"],
    revenueStreams: ["Per-part fees","Design-to-print services","Small-batch runs"],
    kpis: ["Machine utilization","Turnaround time","Repeat orders"],
    legal: "IP considerations when printing client designs; safety protocols for materials.",
    pitfalls: "Underestimating print time/cost; poor finishing quality."
  },

  {
    id: "language-translation",
    title: "Translation & Localization Services",
    type: "service",
    skills: ["bilingual-proficiency","cultural-localization","technical-writing"],
    interests: ["languages","globalization"],
    timePerDay: "2-6 hrs",
    income_1_3_months: "₹10k - ₹1,00,000",
    difficulty: "Medium",
    trend: "Stable",
    summary: "Translate and localize content for businesses expanding to new language markets.",
    how: [
      "Specialize in niche (legal, medical, tech)",
      "Create glossaries & QA workflows",
      "Offer translation + cultural localization",
      "Scale with vetted freelancers"
    ],
    requirements: ["Fluency & domain expertise","CAT tool familiarity"],
    startupCost: "₹2,000 - ₹30,000",
    tools: ["MemoQ/Trados","Google Docs","Notion"],
    marketingChannels: ["LinkedIn","Localization forums","Freelance marketplaces"],
    revenueStreams: ["Per-word fees","Project-based localization","Retainers"],
    kpis: ["Turnaround time","Quality score","Repeat client rate"],
    legal: "Confidentiality for sensitive translations; NDA.",
    pitfalls: "Machine-only translations without localization, missing cultural nuances."
  },

  {
    id: "email-marketing",
    title: "Email Marketing Specialist",
    type: "service",
    skills: ["copywriting","deliverability","automation"],
    interests: ["growth","retention","ecommerce"],
    timePerDay: "1-3 hrs",
    income_1_3_months: "₹10k - ₹1,00,000",
    difficulty: "Medium",
    trend: "High",
    summary: "Design email funnels and automation for businesses to drive repeat sales and retention.",
    how: [
      "Audit current list & flows",
      "Create segmented funnels & lead magnets",
      "Set up automation & A/B test copy",
      "Report on revenue attribution"
    ],
    requirements: ["Understanding of deliverability & segmentation","Template design skills"],
    startupCost: "₹2,000 - ₹25,000",
    tools: ["Klaviyo","Mailchimp","Postman","Google Analytics"],
    marketingChannels: ["On-site popups","Lead magnets","Paid ads to list"],
    revenueStreams: ["Retainer fees","Setup fees","Revenue share"],
    kpis: ["Email revenue","Open & click rates","List growth","Spam complaints"],
    legal: "Comply with anti-spam laws; maintain consent records.",
    pitfalls: "Neglecting list hygiene, poor segmentation, aggressive frequency."
  },

  {
    id: "mobile-app-mvp",
    title: "Mobile App MVP (Startup)",
    type: "product",
    skills: ["product-management","mobile-dev","ux"],
    interests: ["tech","consumer-apps","saas"],
    timePerDay: "2-6 hrs",
    income_1_3_months: "₹0 - ₹2,00,000+",
    difficulty: "High",
    trend: "High",
    summary: "Build a mobile MVP to validate product-market fit; monetize later via subscription or in-app purchases.",
    how: [
      "Validate problem with landing page & waitlist",
      "Build MVP with core feature set",
      "Onboard early users & iterate quickly",
      "Prepare metrics & fundraising materials if needed"
    ],
    requirements: ["Technical team or dev-cofounder","Beta testers"],
    startupCost: "₹50,000 - ₹10,00,000",
    tools: ["React Native/Flutter","Firebase","Stripe","Play Store/App Store"],
    marketingChannels: ["Product Hunt","Beta communities","Influencers"],
    revenueStreams: ["Subscriptions","IAPs","Ads","B2B licensing"],
    kpis: ["WAU/MAU","Retention cohort metrics","CAC","LTV"],
    legal: "App store policies, privacy policy, and data security.",
    pitfalls: "Building unused features, ignoring analytics, poor onboarding."
  },

  {
    id: "voiceover-studio",
    title: "Voiceover & Audio Services",
    type: "service",
    skills: ["voice-acting","audio-editing","scripting"],
    interests: ["media","ads","e-learning"],
    timePerDay: "1-4 hrs",
    income_1_3_months: "₹5k - ₹60k",
    difficulty: "Low",
    trend: "Stable",
    summary: "Provide voiceovers for ads, explainer videos, audiobooks and e-learning content with professional audio quality.",
    how: [
      "Create demos & niche voice reels",
      "List on marketplaces & pitch agencies",
      "Offer packages: raw audio + edited + delivered",
      "Upsell localization and translation with partner network"
    ],
    requirements: ["Good mic & soundproofing","Editing skills (noise reduction)"],
    startupCost: "₹8,000 - ₹60,000",
    tools: ["Audacity/Adobe Audition","Fiverr/Voices.com","Zoom"],
    marketingChannels: ["Freelance marketplaces","LinkedIn","Agency outreach"],
    revenueStreams: ["Per-minute fees","Project licensing","Retainers"],
    kpis: ["Bookings per month","Avg. project value","Client repeat rate"],
    legal: "License terms for commercial use; keep contracts for royalties.",
    pitfalls: "Poor audio quality, unclear usage rights, undercharging long-form projects."
  },

  {
    id: "b2b-lead-gen",
    title: "B2B Lead Generation Service",
    type: "service",
    skills: ["outbound-sales","crm","content"],
    interests: ["sales","b2b","growth"],
    timePerDay: "2-6 hrs",
    income_1_3_months: "₹20k - ₹2,00,000+",
    difficulty: "Medium",
    trend: "High",
    summary: "Provide targeted lead lists and booked meetings for B2B clients using outbound channels.",
    how: [
      "Define ICP & build prospect lists",
      "Run multi-channel outreach (email/LinkedIn/phone)",
      "Book qualified meetings and hand over to sales",
      "Refine based on conversion data"
    ],
    requirements: ["Tools & templates for outreach","Proof of lead quality"],
    startupCost: "₹5,000 - ₹50,000",
    tools: ["PhantomBuster","Apollo","HubSpot","LinkedIn Sales Navigator"],
    marketingChannels: ["LinkedIn outreach","Cold email","Referrals"],
    revenueStreams: ["Per-lead fees","Per-booking fees","Retainers"],
    kpis: ["Qualified meetings","Lead-to-opportunity rate","CAC"],
    legal: "Comply with spam & data laws; maintain opt-out lists.",
    pitfalls: "Poor targeting, low quality leads, over-reliance on one channel."
  },

  {
    id: "mental-health-coach",
    title: "Mental Health & Wellness Coaching",
    type: "service",
    skills: ["coaching","active-listening","behavioral-techniques"],
    interests: ["wellness","self-help","psychology"],
    timePerDay: "1-4 hrs",
    income_1_3_months: "₹10k - ₹1,00,000",
    difficulty: "Medium",
    trend: "High",
    summary: "Offer coaching sessions, workshops and digital products to help clients with stress, routines & habits.",
    how: [
      "Gain certifications (where applicable)",
      "Create frameworks & session packages",
      "Offer group programs & one-on-one coaching",
      "Build content to attract organic clients"
    ],
    requirements: ["Relevant certification & supervision","Ethical boundaries knowledge"],
    startupCost: "₹2,000 - ₹50,000",
    tools: ["Zoom","Calendly","Notion","Payment gateways"],
    marketingChannels: ["Podcast/YouTube","Referrals","Ads targeting wellbeing"],
    revenueStreams: ["Session fees","Group programs","Digital resources"],
    kpis: ["Client retention","Outcome metrics","Referral rate"],
    legal: "Clear scope: coaching vs therapy; informed consent and emergency protocols.",
    pitfalls: "Practicing beyond scope, lack of supervision, poor documentation."
  },
  
  {
    id: BHURUUKfaceless-youtube",
    title: "BHRUKnbFaceless YouTube Channel",
    type: "service",
    skills: ["video-editing","script-research","seo"],
    interests: ["media","education","storytelling"],
    timePerDay: "2-4 hrs",
    income_1_3_months: "₹5k – ₹40k",
    difficulty: "Medium",
    trend: "High",
    summary: "Create high-quality faceless YouTube videos in explainer or compilation niches and monetize via AdSense and sponsorships.",
    how: [
      "Pick a high-demand niche (tech, finance, motivation)",
      "Batch-write 5 scripts and use AI voice-overs",
      "Edit videos with stock footage & dynamic captions",
      "Upload weekly and optimize SEO + thumbnails",
      "Monetize with ads, affiliates, or digital products"
    ]
  },
  {
    id: "youtube-shorts-channel",
    title: "YouTube Shorts Compilation Channel",
    type: "service",
    skills: ["video-editing","social-media","analytics"],
    interests: ["entertainment","pop-culture"],
    timePerDay: "1-3 hrs",
    income_1_3_months: "₹2k – ₹25k",
    difficulty: "Low",
    trend: "Very High",
    summary: "Capitalize on short-form trends by curating viral clips and repurposing them with captions and trending sounds.",
    how: [
      "Identify trending niches (memes, motivation, news)",
      "Download clips under fair-use or royalty-free",
      "Add text overlays & trending music",
      "Post 3-5 Shorts daily and test hashtags",
      "Monetize with channel memberships or ads"
    ]
  },
  {
    id: "podcast-show",
    title: "Podcast Show (Audio + Video)",
    type: "service",
    skills: ["communication","editing","networking"],
    interests: ["conversation","education","culture"],
    timePerDay: "3-5 hrs",
    income_1_3_months: "₹0 – ₹20k",
    difficulty: "Medium",
    trend: "High",
    summary: "Host topic-based podcasts, build an audience, and earn through sponsorships, Patreon, or YouTube clips.",
    how: [
      "Pick a specific theme and format (solo, interview)",
      "Record 5 episodes with decent audio setup",
      "Publish on Spotify, YouTube, and Apple Podcasts",
      "Repurpose content into reels and blog posts",
      "Pitch sponsors after 1k monthly listeners"
    ]
  },
  {
    id: "blogging-seo",
    title: "Blogging with SEO & Affiliate Monetization",
    type: "product",
    skills: ["seo","writing","research"],
    interests: ["marketing","tech","lifestyle"],
    timePerDay: "2-4 hrs",
    income_1_3_months: "₹3k – ₹50k",
    difficulty: "Medium",
    trend: "Medium",
    summary: "Build a niche blog optimized for search traffic and earn via AdSense and affiliate programs.",
    how: [
      "Select evergreen niche & keywords",
      "Set up WordPress with SEO plugins",
      "Write 30 high-value articles",
      "Build backlinks & promote on Pinterest",
      "Monetize via ads and affiliates"
    ]
  },
  {
    id: "newsletter-business",
    title: "Niche Newsletter Monetization",
    type: "service",
    skills: ["writing","email-marketing","research"],
    interests: ["finance","tech","education"],
    timePerDay: "1-2 hrs",
    income_1_3_months: "₹1k – ₹15k",
    difficulty: "Low",
    trend: "High",
    summary: "Create and grow a niche email newsletter, monetize with sponsors and premium content.",
    how: [
      "Pick a topic (e.g., AI tools, personal finance)",
      "Use Beehiiv/Substack for setup",
      "Publish 2 emails per week",
      "Promote via LinkedIn and Reddit communities",
      "Sell ad slots or paid subscriptions"
    ]
  },
  {
    id: "ugc-creator",
    title: "UGC Creator (User-Generated Content)",
    type: "service",
    skills: ["videography","storytelling","marketing"],
    interests: ["fashion","beauty","travel"],
    timePerDay: "1-3 hrs",
    income_1_3_months: "₹10k – ₹60k",
    difficulty: "Medium",
    trend: "Very High",
    summary: "Create short vertical videos for brands without needing your own audience and get paid per project.",
    how: [
      "Build portfolio of 10 sample UGC videos",
      "Reach out to brands via UGC marketplaces",
      "Deliver high-quality shots with scripts",
      "Negotiate usage rights and pricing",
      "Upsell monthly content packages"
    ]
  },
  {
    id: "medium-writer",
    title: "Medium Writer (Monetized Blogging)",
    type: "service",
    skills: ["writing","storytelling","content-marketing"],
    interests: ["self-improvement","tech","creativity"],
    timePerDay: "1-2 hrs",
    income_1_3_months: "₹2k – ₹20k",
    difficulty: "Low",
    trend: "Medium",
    summary: "Write and publish articles on Medium and earn through the Partner Program based on read time.",
    how: [
      "Write daily on popular tags (AI, productivity)",
      "Engage with publications for reach",
      "Use strong titles and storytelling",
      "Repurpose content on LinkedIn & X",
      "Scale via affiliate links in articles"
    ]
  },
  {
    id: "e-book-author",
    title: "Self-Published E-book Author",
    type: "product",
    skills: ["writing","research","design"],
    interests: ["education","fiction","marketing"],
    timePerDay: "2-4 hrs",
    income_1_3_months: "₹3k – ₹40k",
    difficulty: "Medium",
    trend: "Medium",
    summary: "Write and self-publish e-books on Amazon KDP or Gumroad to build a passive income stream.",
    how: [
      "Research a high-demand topic or genre",
      "Outline & write chapters",
      "Design a professional cover",
      "Publish and run small ad campaigns",
      "Collect reviews and update monthly"
    ]
  },
  {
    id: "stock-photography",
    title: "Stock Photography Business",
    type: "product",
    skills: ["photography","editing","marketing"],
    interests: ["travel","design","nature"],
    timePerDay: "1-2 hrs",
    income_1_3_months: "₹1k – ₹10k",
    difficulty: "Low",
    trend: "Medium",
    summary: "Upload high-quality photos to stock sites like Pexels and Shutterstock for royalty income.",
    how: [
      "Shoot niche photos (tech, work spaces, people)",
      "Edit and tag strategically",
      "Upload 100+ images monthly",
      "Track downloads and optimize keywords",
      "Promote portfolio on social media"
    ]
  },
  {
    id: "voiceover-artist",
    title: "Voice-Over Artist (Freelance or YouTube)",
    type: "service",
    skills: ["voice-modulation","audio-editing","communication"],
    interests: ["storytelling","media"],
    timePerDay: "1-3 hrs",
    income_1_3_months: "₹5k – ₹40k",
    difficulty: "Medium",
    trend: "Medium",
    summary: "Offer voice-overs for YouTube videos, ads, and audiobooks through Fiverr and social platforms.",
    how: [
      "Record demo reels in varied tones",
      "Create profile on freelance sites",
      "Offer per-minute pricing tiers",
      "Promote via LinkedIn and Discord",
      "Deliver quick turnarounds for ratings"
    ]
  }
  


];
